[cmake] Added a missing declaration in subroutine check_sizes
[ 70%] Building Fortran object CMakeFiles/Post_processing.dir/c_/HOS-ocean/sourc
es/PostProcessing/reconstruction.f90.obj
c:/HOS-ocean/sources/PostProcessing/reconstruction.f90:483.55:

SUBROUTINE check_sizes(n2,x_min,x_max,y_min,y_max,z_min,t_min,t_max,xlen_star,y
                                                       1
Error: Symbol 'z_min' at (1) has no IMPLICIT type
make[2]: *** [CMakeFiles/Post_processing.dir/c_/HOS-ocean/sources/PostProcessing
/reconstruction.f90.obj] Error 1
make[1]: *** [CMakeFiles/Post_processing.dir/all] Error 2
make: *** [all] Error 2